services:
    LSB\UtilityBundle\Manager\ObjectManager:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'

    lsb_utility_object_manager:
        alias: 'LSB\UtilityBundle\Manager\ObjectManager'

    LSB\UtilityBundle\Manager\ObjectManagerInterface: '@LSB\UtilityBundle\Manager\ObjectManager'

    lsb_utility.manager.container:
        class: 'LSB\UtilityBundle\Service\ManagerContainer'

    LSB\UtilityBundle\Service\ManagerContainerInterface: '@lsb_utility.manager.container'

    LSB\UtilityBundle\Form\EntityLazyType:
        arguments: ['@LSB\UtilityBundle\Manager\ObjectManager']
        tags:
            - { name: form.type }

    ### Serializer

    lsb_utility.jms.serializer.existing_object_constructor:
        class: 'LSB\UtilityBundle\Serializer\ObjectConstructor\ExistingObjectConstructor'
        arguments:
            - '@jms_serializer.unserialize_object_constructor'

    lsb_utility.jms.serializer.handler.money:
        class: 'LSB\UtilityBundle\Serializer\Handler\MoneyHandler'
        tags:
            - { name: jms_serializer.subscribing_handler }

    lsb_utility.jms.serializer.handler.value:
        class: 'LSB\UtilityBundle\Serializer\Handler\ValueHandler'
        tags:
            - { name: jms_serializer.subscribing_handler }

    ### DTO

    LSB\UtilityBundle\DTO\DTOService:
        arguments:
            - '@lsb_utility.manager.container'
            - '@lsb_utility.dto.data_transformer.service'
            - '@security.authorization_checker'
            - '@knp_paginator'
            - '@lsb_utility.dto.resource.helper'
            - '@request_stack'

    lsb_utility.dto.service:
        alias: 'LSB\UtilityBundle\DTO\DTOService'

    LSB\UtilityBundle\DTO\Resource\ResourceHelper:
        arguments:
            - '@lsb_utility.manager.container'

    lsb_utility.dto.resource.helper:
        alias: 'LSB\UtilityBundle\DTO\Resource\ResourceHelper'


    LSB\UtilityBundle\DTO\Resolver\APIRequestResolver:
        arguments:
            - '@validator'
            - '@jms_serializer'
        tags:
            - { name: controller.argument_value_resolver }

    LSB\UtilityBundle\DTO\DataTransformer\DataTransformerModuleInventory: ~

    lsb_utility.dto.data_transformer.module.inventory:
        alias: 'LSB\UtilityBundle\DTO\DataTransformer\DataTransformerModuleInventory'

    LSB\UtilityBundle\DTO\DataTransformer\DataTransformerModuleService:
        arguments:
            - '@lsb_utility.dto.data_transformer.module.inventory'

    lsb_utility.dto.data_transformer.module.service:
        alias: 'LSB\UtilityBundle\DTO\DataTransformer\DataTransformerModuleService'

    LSB\UtilityBundle\DTO\DataTransformer\DataTransformerService:
        arguments:
            - '@lsb_utility.dto.data_transformer.module.service'

    lsb_utility.dto.data_transformer.service: '@LSB\UtilityBundle\DTO\DataTransformer\DataTransformerService'


    LSB\UtilityBundle\Service\ApiVersionGrabber:
        arguments:
            - '@request_stack'

    lsb_utility.api.version_grabber: '@LSB\UtilityBundle\Service\ApiVersionGrabber'

    ### Validator
    LSB\UtilityBundle\Validator\ManagerChoiceValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_choice: '@LSB\UtilityBundle\Validator\ManagerChoiceValidator'

    LSB\UtilityBundle\Validator\ManagerUniqueEntityValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_unique_entity: '@LSB\UtilityBundle\Validator\ManagerUniqueEntityValidator'

    LSB\UtilityBundle\Validator\ManagerCallbackValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_callback: '@LSB\UtilityBundle\Validator\ManagerCallbackValidator'