services:
    LSB\UtilityBundle\Manager\ObjectManager:
        arguments:
            - '@doctrine.orm.default_entity_manager'

    lsb_utility_object_manager:
        alias: 'LSB\UtilityBundle\Manager\ObjectManager'

    LSB\UtilityBundle\Manager\ObjectManagerInterface: '@LSB\UtilityBundle\Manager\ObjectManager'

    LSB\UtilityBundle\Form\EntityLazyType:
        arguments: ['@LSB\UtilityBundle\Manager\ObjectManager']
        tags:
            - { name: form.type }