services:
    LSB\UtilityBundle\Manager\ObjectManager:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@validator'

    lsb_utility_object_manager:
        alias: 'LSB\UtilityBundle\Manager\ObjectManager'

    LSB\UtilityBundle\Manager\ObjectManagerInterface: '@LSB\UtilityBundle\Manager\ObjectManager'

    lsb_utility.manager.container:
        class: 'LSB\UtilityBundle\Service\ManagerContainer'

    LSB\UtilityBundle\Service\ManagerContainerInterface: '@lsb_utility.manager.container'

    LSB\UtilityBundle\Form\EntityLazyType:
        arguments: ['@LSB\UtilityBundle\Manager\ObjectManager']
        tags:
            - { name: form.type }

    ### Serializer

    lsb_utility.jms.serializer.existing_object_constructor:
        class: 'LSB\UtilityBundle\Serializer\ObjectConstructor\ExistingObjectConstructor'
        arguments:
            - '@jms_serializer.unserialize_object_constructor'
            - '@jms_serializer.doctrine_object_constructor'

    lsb_utility.jms.serializer.handler.money:
        class: 'LSB\UtilityBundle\Serializer\Handler\MoneyHandler'
        tags:
            - { name: jms_serializer.subscribing_handler }

    lsb_utility.jms.serializer.handler.value:
        class: 'LSB\UtilityBundle\Serializer\Handler\ValueHandler'
        tags:
            - { name: jms_serializer.subscribing_handler }

    ### DTO

    LSB\UtilityBundle\DataTransfer\DTOService:
        arguments:
            - '@lsb_utility.manager.container'
            - '@lsb_utility.dto.data_transformer.service'
            - '@security.authorization_checker'
            - '@knp_paginator'
            - '@lsb_utility.dto.resource.helper'
            - '@request_stack'

    lsb_utility.dto.service:
        alias: 'LSB\UtilityBundle\DataTransfer\DTOService'

    LSB\UtilityBundle\DataTransfer\Resource\ResourceHelper:
        arguments:
            - '@lsb_utility.manager.container'

    lsb_utility.dto.resource.helper:
        alias: 'LSB\UtilityBundle\DataTransfer\Resource\ResourceHelper'


    LSB\UtilityBundle\DataTransfer\Resolver\APIRequestResolver:
        arguments:
            - '@validator'
            - '@jms_serializer'
        tags:
            - { name: controller.argument_value_resolver }

    LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerModuleInventory: ~

    lsb_utility.dto.data_transformer.module.inventory:
        alias: 'LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerModuleInventory'

    LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerModuleService:
        arguments:
            - '@lsb_utility.dto.data_transformer.module.inventory'

    lsb_utility.dto.data_transformer.module.service:
        alias: 'LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerModuleService'

    LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerService:
        arguments:
            - '@lsb_utility.dto.data_transformer.module.service'

    lsb_utility.dto.data_transformer.service: '@LSB\UtilityBundle\DataTransfer\DataTransformer\DataTransformerService'


    LSB\UtilityBundle\Service\ApiVersionGrabber:
        arguments:
            - '@request_stack'

    lsb_utility.api.version_grabber: '@LSB\UtilityBundle\Service\ApiVersionGrabber'

    ### Helpers

    LSB\UtilityBundle\DataTransfer\Helper\CRUD\Route\NewResourceGetRouteGenerator:
        arguments:
            - '@router'

    lsb_utility.dto.helper.crud.route.generator.new_resource:
        alias: 'LSB\UtilityBundle\DataTransfer\Helper\CRUD\Route\NewResourceGetRouteGenerator'

    LSB\UtilityBundle\DataTransfer\Helper\CRUD\Route\RouteGeneratorInterface:
        alias: 'LSB\UtilityBundle\DataTransfer\Helper\CRUD\Route\NewResourceGetRouteGenerator'

    ### Validator

    LSB\UtilityBundle\Validator\ManagerChoiceValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_choice: '@LSB\UtilityBundle\Validator\ManagerChoiceValidator'

    LSB\UtilityBundle\Validator\ManagerUniqueEntityValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_unique_entity: '@LSB\UtilityBundle\Validator\ManagerUniqueEntityValidator'

    LSB\UtilityBundle\Validator\ManagerCallbackValidator:
        arguments:
            - '@lsb_utility.manager.container'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.manager_callback: '@LSB\UtilityBundle\Validator\ManagerCallbackValidator'

    #### Value

    LSB\UtilityBundle\Validator\ValueNotEqualToValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_not_equal_to: '@LSB\UtilityBundle\Validator\ValueNotEqualToValidator'

    LSB\UtilityBundle\Validator\ValueEqualToValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_equal_to: '@LSB\UtilityBundle\Validator\ValueEqualToValidator'

    LSB\UtilityBundle\Validator\ValueGreaterThanValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_greater_than: '@LSB\UtilityBundle\Validator\ValueGraterThanValidator'

    LSB\UtilityBundle\Validator\ValueGreaterThanOrEqualValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_greater_than_or_equal: '@LSB\UtilityBundle\Validator\ValueGreaterThanOrEqualValidator'

    LSB\UtilityBundle\Validator\ValueLessThanValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_less_than: '@LSB\UtilityBundle\Validator\ValueLessThanValidator'

    LSB\UtilityBundle\Validator\ValueLessThanOrEqualValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.value_less_than_or_equal: '@LSB\UtilityBundle\Validator\ValueLessThanOrEqualValidator'

    #### Money

    LSB\UtilityBundle\Validator\MoneyNotEqualToValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_not_equal_to: '@LSB\UtilityBundle\Validator\MoneyNotEqualToValidator'

    LSB\UtilityBundle\Validator\MoneyEqualToValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_equal_to: '@LSB\UtilityBundle\Validator\MoneyEqualToValidator'

    LSB\UtilityBundle\Validator\MoneyGreaterThanValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_greater_than: '@LSB\UtilityBundle\Validator\MoneyGraterThanValidator'

    LSB\UtilityBundle\Validator\MoneyGreaterThanOrEqualValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_greater_than_or_equal: '@LSB\UtilityBundle\Validator\MoneyGreaterThanOrEqualValidator'

    LSB\UtilityBundle\Validator\MoneyLessThanValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_less_than: '@LSB\UtilityBundle\Validator\MoneyLessThanValidator'

    LSB\UtilityBundle\Validator\MoneyLessThanOrEqualValidator:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: validator.constraint_validator }

    lsb_utility.validator.money_less_than_or_equal: '@LSB\UtilityBundle\Validator\MoneyLessThanOrEqualValidator'