<?php

namespace LSB\UtilityBundle\DataTransfer\Builder\Field;

use LSB\UtilityBundle\DataTransfer\Builder\Relation\XRelation;

class AutocompleterXField extends BaseXField
{
    const TYPE = 'autocompleter';

    protected XRelation $relation;

    public function __construct(
        XRelation $relation,
        bool      $isReadOnly = false,
        bool      $isDisabled = false
    ) {
        parent::__construct($isReadOnly, $isDisabled);
        $this->type = self::TYPE;
        $this->relation = $relation;
    }

    public function jsonSerialize(): mixed
    {
        $result = parent::jsonSerialize(); // TODO: Change the autogenerated stub
        $result['relation'] = $this->relation;

        return $result;
    }
}